#!/usr/bin/env python
# -*- coding:utf-8 -*-
# @Time : 2020/5/8 4:23 下午
# @Author : wyf
# @File : myapi
# @Software: PyCharm

import unittest, re, json
import traceback
import requests
from Library import CommonMethod
from Library.Mysqldb import Mysqldb
from Library.log import Logger

ip=CommonMethod.getConfig("url")
login_api=CommonMethod.getConfig("login_api")
class apitest(unittest.TestCase):
    log=Logger("接口自动化")
    s = requests.session()
    @classmethod
    def setUpClass(cls) -> None:
        cls.url=ip
        headers = {
            "Connection": "keep_alive",
            "Content-Type": "application/json;charset=UTF-8",
        }
        data={
            "account":"wanyafei01",
            "password":"9cbf8a4dcb8e30682b927f352d6559a0"
        }
        token=json.loads(cls.s.post(cls.url+login_api, json=data, headers=headers).content)['data']['token']
        cls.token=token


    @classmethod
    def tearDownClass(cls) -> None:
        pass